/**
 * WordPress → Next.js 301 redirect map for the aitoolsset.com cutover.
 *
 * Generated from the live WP sitemap. Only includes paths whose slug
 * changed or whose tool/category was not migrated; unchanged /ai-tool/*
 * and /ai-tools/* slugs resolve directly (trailing slash auto-normalized).
 * Defunct tools 301 to /ai-tools rather than 404.
 */
export const WP_REDIRECTS = [
  { source: "/ai-tool/emojis-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/human-or-not", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/solidpoint-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/dreamina-ai", destination: "/ai-tool/dreamina", permanent: true },
  { source: "/ai-tool/super-logout", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/the-brief", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/gravity-write", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/ltx-studio", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/akool-ai", destination: "/ai-tool/akool", permanent: true },
  { source: "/ai-tool/zyro", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/dubverse-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/mage-space", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/w-okada-voice-changer", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/suno-ai", destination: "/ai-tool/suno", permanent: true },
  { source: "/ai-tool/palette-fm", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/barbergpt-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/coursology", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/gauth", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/polybuzz", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/forex-factory", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/2short-ai", destination: "/ai-tool/2short", permanent: true },
  { source: "/ai-tool/pictory-ai", destination: "/ai-tool/pictory", permanent: true },
  { source: "/ai-tool/synthesia-ai", destination: "/ai-tool/synthesia", permanent: true },
  { source: "/ai-tool/jogg-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/lensa-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/getimg-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/dezgo-ai", destination: "/ai-tool/dezgo", permanent: true },
  { source: "/ai-tool/fakeyou-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/unlucid-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/sakura-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/digen-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/andi-search", destination: "/ai-tool/andisearch", permanent: true },
  { source: "/ai-tool/imgcreator-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/ai-time-machine", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/quizbot-ai", destination: "/ai-tool/quizbot", permanent: true },
  { source: "/ai-tool/lensgo", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/playphrase-me", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/pika-labs", destination: "/ai-tool/pika", permanent: true },
  { source: "/ai-tool/star-by-face", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/imagica", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/type-studio", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/whisk-ai", destination: "/ai-tool/whisk", permanent: true },
  { source: "/ai-tool/themetavoice", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/murf", destination: "/ai-tool/murf-ai", permanent: true },
  { source: "/ai-tool/paperanimator", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/pixverse-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/chub-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/venice-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/topview-ai", destination: "/ai-tool/topview", permanent: true },
  { source: "/ai-tool/vmate-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/kirkify-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/raphael-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/ocean-orchestrator", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/codex-subagents", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/permit-io", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/lalal-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/axiom", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/designs-ai", destination: "/ai-tools", permanent: true },
  { source: "/ai-tool/vocaloid", destination: "/ai-tools", permanent: true },
  { source: "/ai-tools/ai-agent", destination: "/ai-tools/ai-agents", permanent: true },
  { source: "/ai-tools/design", destination: "/ai-tools/design-generators", permanent: true },
  { source: "/ai-tools/image", destination: "/ai-tools/image-generators", permanent: true },
  { source: "/ai-tools/spreadsheets", destination: "/ai-tools/data-analysis", permanent: true },
  { source: "/ai-tools/website-builder", destination: "/ai-tools/website-builders", permanent: true },
  { source: "/ai-tools/writing", destination: "/ai-tools/writing-generators", permanent: true },
  { source: "/ai-tools/creative", destination: "/ai-tools/design-generators", permanent: true },
  { source: "/ai-tools/popular", destination: "/ai-tools", permanent: true },
  { source: "/ai-tools/trending", destination: "/ai-tools", permanent: true },
  { source: "/privacy-policy", destination: "/privacy", permanent: true },
  { source: "/submit-tool", destination: "/submit", permanent: true },
  { source: "/ai-tools-category", destination: "/ai-tools", permanent: true },
];
