export type GlossaryTerm = {
  term: string;
  acro?: string;
  cat: "core" | "models" | "training" | "agents";
  def: string;
  example?: string;
  related: string[];
  tool?: { name: string; domain: string };
};

export const GLOSSARY: GlossaryTerm[] = [
  { term: "Agentic AI", cat: "agents", def: "AI systems that can <strong>plan, execute, and self-correct</strong> over multi-step tasks autonomously, rather than just answering one question at a time. They use tools, browse the web, and iterate on goals.", example: "A coding agent that reads a bug report, locates the file, writes a fix, runs the tests, and opens a pull request — all without human intervention.", related: ["LLM agent", "Tool use", "MCP", "Autonomy"], tool: { name: "Cursor", domain: "cursor.sh" } },
  { term: "AGI", acro: "Artificial General Intelligence", cat: "core", def: "A hypothetical AI that can perform <strong>any intellectual task a human can</strong>, across any domain. Current AI is \"narrow\" — it's superhuman at chess or coding but useless at unrelated tasks. AGI would generalize.", example: "An AGI could read a medical paper, then turn around and design a bridge, then debug a Linux kernel — at expert level in all three.", related: ["ASI", "Narrow AI", "LLM"] },
  { term: "Attention", cat: "models", def: "The mechanism that lets a transformer model \"<strong>look at all words at once</strong>\" and decide which ones matter for predicting the next one. It's why ChatGPT can resolve \"it\" in long sentences.", example: "In \"The cat sat on the mat because it was warm,\" attention helps the model link \"it\" → \"mat\" or \"cat\" based on context.", related: ["Transformer", "Context window", "Self-attention"] },
  { term: "Batch inference", cat: "training", def: "Running many prompts through a model <strong>at once</strong> instead of one at a time. Cheaper and faster per request, but with higher latency for any individual response.", example: "OpenAI offers a Batch API that's 50% cheaper than real-time — perfect for embedding 1M documents overnight.", related: ["Inference", "Throughput"] },
  { term: "Chain of Thought", acro: "CoT", cat: "core", def: "A prompting technique where you ask the model to <strong>\"think step by step\"</strong> before answering. Dramatically improves accuracy on math, logic, and reasoning tasks.", example: "Prompt: \"Let's think step by step. First, identify the variables…\" — turns a wrong answer into a right one on multi-step problems.", related: ["Prompt engineering", "Reasoning", "Test-time compute"] },
  { term: "Context window", cat: "models", def: "The maximum amount of text (measured in tokens) a model can \"<strong>see at once</strong>.\" Bigger = it can read more of your codebase, document, or chat history in a single call.", example: "GPT-5 has a 1M token context (~750K words). Claude 4 has 500K. GPT-3.5 had only 4K — a huge limitation back then.", related: ["Token", "RAG", "Long context"] },
  { term: "Deep research", cat: "agents", def: "An agentic mode where the AI <strong>autonomously searches the web</strong> for 5–30 minutes, reads dozens of sources, and produces a long, cited report. Pioneered by OpenAI and Google.", example: "\"Write a deep research report on Series A funding trends in AI agents in 2025\" — returns a 15-page cited document.", related: ["Agentic AI", "RAG", "Web browsing"] },
  { term: "Diffusion model", cat: "models", def: "The class of AI that powers <strong>image generators</strong> like Midjourney and Stable Diffusion. It learns to reverse the process of adding noise to an image, gradually \"denoising\" random pixels into a coherent picture.", example: "Type \"a cat astronaut on Mars\" — the model starts with TV static and iteratively shapes it into your image.", related: ["GAN", "Latent space", "Image generation"] },
  { term: "Embeddings", cat: "core", def: "A way of representing text (or images, audio) as a <strong>list of numbers</strong> that captures meaning. Two pieces of text with similar meaning will have similar embeddings.", example: "\"Dog\" and \"puppy\" have nearly identical embeddings. \"Dog\" and \"spreadsheet\" are far apart. This is how semantic search works.", related: ["Vector database", "RAG", "Semantic search"] },
  { term: "Fine-tuning", cat: "training", def: "Taking a pre-trained model and <strong>training it further on your own data</strong> so it learns your style, domain, or task better. Cheaper than training from scratch.", example: "A law firm fine-tunes GPT-4o on its case archive so the AI writes briefs in the firm's specific voice and citation style.", related: ["LoRA", "Pre-training", "RLHF"] },
  { term: "GPT", acro: "Generative Pre-trained Transformer", cat: "models", def: "OpenAI's family of language models. \"Generative\" (it creates text), \"Pre-trained\" (on most of the internet), \"Transformer\" (the underlying architecture).", example: "GPT-2 (2019), GPT-3 (2020), GPT-4 (2023), GPT-5 (2026) — each generation roughly 10× larger and smarter.", related: ["LLM", "Transformer", "OpenAI"], tool: { name: "ChatGPT", domain: "chat.openai.com" } },
  { term: "Hallucination", cat: "core", def: "When an AI <strong>confidently states something false</strong>. The model isn't lying — it's generating plausible-sounding text based on patterns, and sometimes those patterns produce wrong facts.", example: "Asking GPT-4 about a 2024 court case it didn't see in training — it may invent a fake citation that looks real.", related: ["Grounding", "RAG", "Reliability"] },
  { term: "Inference", cat: "core", def: "When the model is <strong>running</strong> — generating output for a user query. Different from training, which is when the model learns. Inference is what costs money per API call.", example: "You type a prompt — the model runs inference for ~2 seconds — you get a response. That single call costs $0.0001–$0.10.", related: ["Training", "Tokens per second", "Latency"] },
  { term: "LLM", acro: "Large Language Model", cat: "models", def: "A neural network trained on <strong>massive amounts of text</strong> to predict the next word. The category includes GPT, Claude, Gemini, Llama, etc. \"Large\" usually means 1B+ parameters.", example: "When you ask ChatGPT a question, an LLM predicts each word one at a time, considering everything that came before.", related: ["Transformer", "GPT", "Parameters"] },
  { term: "LoRA", acro: "Low-Rank Adaptation", cat: "training", def: "A way to fine-tune a model by adding a <strong>small \"adapter\"</strong> instead of retraining the whole thing. 100× cheaper than full fine-tuning, with similar results.", example: "Stable Diffusion users share LoRAs that teach the model specific art styles (e.g. \"anime LoRA,\" \"cyberpunk LoRA\").", related: ["Fine-tuning", "PEFT", "Adapter"] },
  { term: "MCP", acro: "Model Context Protocol", cat: "agents", def: "An open standard from Anthropic that lets AI assistants <strong>plug into external tools</strong> (databases, APIs, file systems) in a uniform way. Think USB-C for AI agents.", example: "Claude Desktop with MCP can query your Postgres database, read your GitHub repos, and edit your local files — all through one protocol.", related: ["Agentic AI", "Tool use", "Function calling"] },
  { term: "Multimodal", cat: "models", def: "A model that can handle <strong>more than one type of input</strong> — typically text, images, audio, and video together. GPT-4o, Gemini, and Claude are all multimodal.", example: "Upload a chart screenshot + ask \"explain this trend\" — multimodal model reads both image and text in one go.", related: ["Vision", "Audio AI", "Modality"] },
  { term: "Parameters", cat: "models", def: "The <strong>\"knobs\"</strong> inside a neural network that get tuned during training. More parameters = more capacity. GPT-3 has 175B parameters. Llama 4 has 405B.", example: "Each parameter is a number. A 70B model = 70 billion numbers. That's why models need GPUs to run.", related: ["Weights", "Model size", "Compute"] },
  { term: "Pre-training", cat: "training", def: "The first, most expensive step of building an AI: feeding it <strong>huge amounts of text from the internet</strong> so it learns language patterns. Costs millions of dollars in GPU time.", example: "GPT-4 was pre-trained on roughly 13 trillion tokens of text — books, web pages, code repositories.", related: ["Fine-tuning", "RLHF", "Foundation model"] },
  { term: "Prompt engineering", cat: "core", def: "The art of <strong>writing instructions</strong> for an AI so it gives you exactly what you want. Bad prompts → bad outputs. Good prompts → magic.", example: "\"Write a poem\" → mediocre. \"Write a 4-stanza sonnet about coffee in the style of Shakespeare, ABAB rhyme scheme\" → great.", related: ["Chain of Thought", "Few-shot", "System prompt"] },
  { term: "RAG", acro: "Retrieval-Augmented Generation", cat: "core", def: "A technique that lets the AI <strong>look up information</strong> from a database or document collection before answering, instead of relying only on what it learned in training.", example: "You ask \"What's our company's refund policy?\" → RAG retrieves the relevant page from your internal docs → AI answers using that.", related: ["Embeddings", "Vector database", "Grounding"] },
  { term: "Reasoning model", cat: "models", def: "A class of model (e.g. OpenAI o1, DeepSeek R1) that <strong>\"thinks\" before responding</strong>, using extra compute at inference time to work through hard problems step by step.", example: "Standard model: instant answer. Reasoning model: 15-second pause, then a much better answer for math/code/logic tasks.", related: ["Test-time compute", "Chain of Thought", "o1"] },
  { term: "RLHF", acro: "Reinforcement Learning from Human Feedback", cat: "training", def: "The training step that <strong>aligns AI behavior</strong> with human preferences. Humans rate model responses; the model learns to produce responses humans prefer.", example: "RLHF is why ChatGPT is polite, helpful, and refuses harmful requests — it was rewarded by humans for that behavior.", related: ["Alignment", "Fine-tuning", "DPO"] },
  { term: "Temperature", cat: "core", def: "A setting (0–2) that controls <strong>how random the output is</strong>. Low = deterministic and focused. High = creative and varied. 0.7 is the typical default.", example: "Code generation: use temperature 0 for consistency. Creative writing: use 0.9 for variety.", related: ["Top-p", "Sampling", "Determinism"] },
  { term: "Test-time compute", cat: "models", def: "How much <strong>thinking time</strong> the model uses when answering. New reasoning models (o1, o3) get smarter by spending more compute at inference, not just at training time.", example: "30 seconds of test-time compute on a math problem can match a 10× larger model running normally. Tradeoff: cost and latency.", related: ["Reasoning model", "Inference", "Chain of Thought"] },
  { term: "Token", cat: "core", def: "The basic unit of text an LLM processes. Roughly <strong>¾ of a word</strong> in English. \"ChatGPT is amazing\" → 5 tokens. API pricing is per token.", example: "1M tokens ≈ 750K words ≈ a 1,500-page novel. GPT-4 charges $30 per 1M output tokens.", related: ["Context window", "Tokenizer", "Pricing"] },
  { term: "Tool use", cat: "agents", def: "When an AI is allowed to <strong>call external functions</strong> — search the web, run code, look up a database, send an email. Critical capability for agents.", example: "You ask \"what's the weather in Tokyo?\" — AI doesn't guess, it calls a weather API and reports back.", related: ["Function calling", "Agentic AI", "MCP"] },
  { term: "Transformer", cat: "models", def: "The neural network architecture that powers <strong>every modern LLM</strong>. Introduced by Google in 2017 (\"Attention Is All You Need\"). Replaced earlier RNN-based models.", example: "GPT, Claude, Gemini, Llama, Mistral — all transformers. The \"T\" in GPT stands for Transformer.", related: ["Attention", "LLM", "Neural network"] },
  { term: "Vector database", cat: "core", def: "A specialised database for storing and searching <strong>embeddings</strong>. Lets you find \"semantically similar\" items quickly — the backbone of RAG, recommendation engines, and semantic search.", example: "Pinecone, Weaviate, Chroma are popular vector DBs. Store 10M document embeddings → find the 5 closest in milliseconds.", related: ["Embeddings", "RAG", "Semantic search"] },
  { term: "Vibe coding", cat: "agents", def: "A term coined by Andrej Karpathy for <strong>building software by describing it in plain English</strong> to an AI agent, accepting whatever it writes without reading the code carefully.", example: "\"Build me a Twitter clone with dark mode and a feed\" — AI scaffolds the entire app. You test, refine, ship.", related: ["Agentic AI", "No-code", "Cursor"] },
  { term: "Vision-language model", acro: "VLM", cat: "models", def: "A model that can <strong>see images and produce text</strong>. Lets you upload a photo and ask questions about it.", example: "GPT-4V can read a screenshot of your code, identify the bug, and suggest the fix.", related: ["Multimodal", "OCR", "Image understanding"] },
  { term: "Zero-shot", cat: "core", def: "Asking the AI to do a task with <strong>no examples</strong> in the prompt. Modern LLMs are good at this — but few-shot (with examples) usually works better.", example: "Zero-shot: \"Translate this to French: hello.\" Few-shot: \"Translate: 'dog'→'chien'. 'cat'→'chat'. Now: 'hello'→\"", related: ["Few-shot", "In-context learning", "Prompt"] },
];

export function slugifyTerm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
